name: baby-1l-run-4
channels:
  - conda-forge
dependencies:
  - python
  - openmc # add version tag
  - openmc-plotter
  - numpy # add version tag
  - scipy # add version tag
  - matplotlib # add version tag
  - sympy
  - pandas
  - pint-pandas
  - nbconvert
  - ipykernel
  - pint
  - pip
  - pip:
      - libra-toolbox==0.9.2
      - openmc_data_downloader
      - matplotlib-label-lines
      - h-transport-materials
      - pathsim
